 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [13/Sep/2023 03:17:52] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:18:00] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:22:15] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:22:15] "GET / HTTP/1.0" 200 -
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debug mode: off
Address already in use
Port 5011 is in use by another program. Either identify and stop that program, or start the server with a different port.
127.0.0.1 - - [13/Sep/2023 03:27:28] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:27:30] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:27:48] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:27:56] "GET / HTTP/1.0" 200 -
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
127.0.0.1 - - [13/Sep/2023 03:30:03] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:30:03] "GET /static/img/flask.png HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:30:03] "GET /static/img/API.png HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:30:03] "GET /static/img/react.png HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:30:03] "GET /static/css/style.css HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:03] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:03] "GET /static/img/flask.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:03] "GET /static/img/react.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:03] "GET /static/img/API.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:34] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:35] "GET /static/img/flask.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:35] "GET /static/css/style.css HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:35] "GET /static/img/API.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:35] "GET /static/img/react.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:35] "GET /favicon.ico HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:35:42] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:35:42] "GET /static/img/autism_hero.jpg HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:36:16] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:36:20] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:36:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:36:25] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:14] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:16] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:23] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:24] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:25] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:25] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:26] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:27] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:31] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:32] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:37:32] "GET /static/img/autism_hero.jpg HTTP/1.0" 304 -
127.0.0.1 - - [13/Sep/2023 03:37:46] "GET /project/python_portfolio HTTP/1.0" 200 -
 * Serving Flask app 'app/__init__.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
[2023-09-13 03:39:06,272] ERROR in app: Exception on /project/python_portfolio [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 54, in project
    return render_template(f"project_{slug}.html", project=slug_to_project[slug])
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: project_python_portfolio.html
127.0.0.1 - - [13/Sep/2023 03:39:06] "GET /project/python_portfolio HTTP/1.0" 500 -
[2023-09-13 03:39:07,522] ERROR in app: Exception on /project/python_portfolio [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 54, in project
    return render_template(f"project_{slug}.html", project=slug_to_project[slug])
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: project_python_portfolio.html
127.0.0.1 - - [13/Sep/2023 03:39:07] "GET /project/python_portfolio HTTP/1.0" 500 -
[2023-09-13 03:39:19,221] ERROR in app: Exception on /project/python_portfolio [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 54, in project
    return render_template(f"project_{slug}.html", project=slug_to_project[slug])
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: project_python_portfolio.html
127.0.0.1 - - [13/Sep/2023 03:39:19] "GET /project/python_portfolio HTTP/1.0" 500 -
 * Serving Flask app 'app/__init__.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
[2023-09-13 03:40:02,569] ERROR in app: Exception on /project/python_portfolio [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 54, in project
    return render_template(f"project_{slug}.html", project=slug_to_project[slug])
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: project_python_portfolio.html
127.0.0.1 - - [13/Sep/2023 03:40:02] "GET /project/python_portfolio HTTP/1.0" 500 -
[2023-09-13 03:40:04,091] ERROR in app: Exception on /project/python_portfolio [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 54, in project
    return render_template(f"project_{slug}.html", project=slug_to_project[slug])
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: project_python_portfolio.html
127.0.0.1 - - [13/Sep/2023 03:40:04] "GET /project/python_portfolio HTTP/1.0" 500 -
[2023-09-13 03:40:09,985] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:40:09] "GET / HTTP/1.0" 500 -
 * Serving Flask app 'app/__init__.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
[2023-09-13 03:41:16,645] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:41:16] "GET / HTTP/1.0" 500 -
[2023-09-13 03:41:18,560] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:41:18] "GET / HTTP/1.0" 500 -
[2023-09-13 03:42:28,879] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:42:28] "GET / HTTP/1.0" 500 -
 * Serving Flask app 'app/__init__.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
[2023-09-13 03:43:11,013] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:43:11] "GET / HTTP/1.0" 500 -
[2023-09-13 03:43:18,349] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:43:18] "GET / HTTP/1.0" 500 -
[2023-09-13 03:43:18,544] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/oackland/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1341, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1281, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 59, in page_not_found
    return render_template("404.html"), 404
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
127.0.0.1 - - [13/Sep/2023 03:43:18] "GET /favicon.ico HTTP/1.0" 500 -
[2023-09-13 03:43:21,405] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 37, in home
    return render_template("home.html", projects=projects)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/.local/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
127.0.0.1 - - [13/Sep/2023 03:43:21] "GET / HTTP/1.0" 500 -
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
127.0.0.1 - - [13/Sep/2023 03:44:46] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:45:00] "GET / HTTP/1.0" 200 -
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 03:45:31] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:45:33] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:45:35] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:45:38] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:45:38] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:46:09] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:46:11] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:46:12] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:46:13] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:46:14] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:46:43] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:47:01] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:47:02] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:47:35] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:47:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:47:44] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:48:00] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:48:47] "GET /project/python_portfolioww HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:48:47] "GET /static/img/4041.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:48:57] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:48:58] "GET /project/python_portfolio HTTP/1.0" 200 -
 * Detected change in '/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py', reloading
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 03:51:31] "GET /project/python_portfolio HTTP/1.0" 200 -
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5011
 * Running on http://96.73.17.121:5011
Press CTRL+C to quit
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 03:53:08] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:32] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:33] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:35] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:36] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:37] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:40] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:55] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:56] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:53:57] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:55:55] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:55:55] "GET /static/img/pointer.svg HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:56:22] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:56:36] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:56:52] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:56:52] "GET /static/img/pointer.svg HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 03:57:16] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:57:17] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:57:18] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:57:26] "GET /project/IN%20PROGRESS HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py", line 54, in project
    return render_template(f"project_{slug}.html", project=slug_to_project[slug])
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "/home/oackland/personal_projects/myWebApps/testing_docker/venv/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: project_IN PROGRESS.html
127.0.0.1 - - [13/Sep/2023 03:57:27] "GET /project/IN%20PROGRESS?__debugger__=yes&cmd=resource&f=style.css HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:57:27] "GET /project/IN%20PROGRESS?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:57:27] "GET /project/IN%20PROGRESS?__debugger__=yes&cmd=resource&f=console.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:57:27] "GET /project/IN%20PROGRESS?__debugger__=yes&cmd=resource&f=console.png HTTP/1.0" 304 -
127.0.0.1 - - [13/Sep/2023 03:58:00] "GET / HTTP/1.0" 200 -
 * Detected change in '/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py', reloading
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 03:58:53] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:59:11] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:59:12] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 03:59:12] "GET /static/img/pointer.svg HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 04:00:07] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:00:07] "GET /static/img/pointer.svg HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 04:00:27] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:07] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:32] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:39] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:39] "GET /static/css/style.css HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:39] "GET /static/img/API.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:39] "GET /static/img/flask.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:39] "GET /static/img/react.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:59] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:01:59] "GET /static/img/pointer.svg HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 04:02:02] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:45] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:47] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:48] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:50] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:51] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:52] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:53] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:02:53] "GET /project/python_portfolio HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:29] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:29] "GET /static/img/flask.png HTTP/1.0" 304 -
127.0.0.1 - - [13/Sep/2023 04:04:29] "GET /static/img/react.png HTTP/1.0" 304 -
127.0.0.1 - - [13/Sep/2023 04:04:29] "GET /static/css/style.css HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:29] "GET /static/img/API.png HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:29] "GET /favicon.ico HTTP/1.0" 404 -
127.0.0.1 - - [13/Sep/2023 04:04:38] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:43] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:44] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:44] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:46] "GET /about HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:47] "GET /contact HTTP/1.0" 200 -
127.0.0.1 - - [13/Sep/2023 04:04:48] "GET / HTTP/1.0" 200 -
 * Detected change in '/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py', reloading
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 04:06:00] "GET / HTTP/1.0" 200 -
 * Detected change in '/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py', reloading
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 04:06:56] "GET / HTTP/1.0" 200 -
 * Detected change in '/home/oackland/personal_projects/myWebApps/testing_docker/app/__init__.py', reloading
 * Restarting with stat
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: 470-298-616
127.0.0.1 - - [13/Sep/2023 04:08:13] "GET / HTTP/1.0" 200 -
